import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { NotificationRecipientType, Prisma, SocialModerationAction, SocialPostStatus, SocialPostVisibility, SocialReportReason, SocialReportSeverity, SocialReportStatus, UserRole } from '@prisma/client';
import { AuthUserContext } from '../../common/decorators/current-user.decorator';
import { AuditLogWriterService } from '../../common/services/audit-log.service';
import { SOCIAL_REPORT_INCLUDE, SocialModerationRepository } from './social-moderation.repository';
import { SocialReportingRulesRepository } from './social-reporting-rules.repository';
import { AllSocialReportReason, AllSocialReportStatus, AllSocialSeverity, CreateSocialReportingRuleDto, ExportFormat, ExportSocialReportsDto, ExportSocialRulesDto, ListSocialReportingRulesDto, ListSocialReportsDto, RuleSortBy, SocialModerationActionDto, SocialModerationStatsDto, SocialRange, SocialSortBy, SortOrder, UpdateSocialReportingRuleDto, UpdateSocialReportingRuleStatusDto } from './dto/social-moderation.dto';

type ReportView = Prisma.SocialReportGetPayload<{ include: typeof SOCIAL_REPORT_INCLUDE }>;
type RuleView = Prisma.SocialReportingRuleGetPayload<object>;
type FileResult = { content: string; filename: string; contentType: string };

@Injectable()
export class SocialModerationService {
  constructor(private readonly socialModerationRepository: SocialModerationRepository, private readonly socialReportingRulesRepository: SocialReportingRulesRepository, private readonly auditLog: AuditLogWriterService) {}

  async stats(query: SocialModerationStatsDto) {
    const where = this.dateWhere(query);
    const [totalFlaggedPosts, pendingReports, highSeverityReports, removedPosts, hiddenPosts, warningsSent] = await this.socialModerationRepository.findStatsRows(where);
    return { data: { totalFlaggedPosts, pendingReports, highSeverityReports, removedPosts, hiddenPosts, warningsSent }, message: 'Social moderation stats fetched successfully.' };
  }

  async reports(query: ListSocialReportsDto) {
    const page = query.page ?? 1; const limit = Math.min(query.limit ?? 20, 100); const where = this.reportWhere(query);
    const [items, total] = await this.socialModerationRepository.findReportsAndCount({ where, orderBy: this.reportOrder(query.sortBy, query.sortOrder), skip: (page - 1) * limit, take: limit });
    return { data: items.map((item) => this.reportListItem(item)), meta: { page, limit, total, totalPages: Math.ceil(total / limit) }, message: 'Social reports fetched successfully.' };
  }

  async reportDetails(id: string) {
    const report = await this.findReport(id);
    const history = await this.socialModerationRepository.findReportHistory(report.postId);
    return { data: { id: report.id, reportId: report.reportId, status: report.status, severity: report.severity, post: { id: report.post.id, content: report.post.content, mediaUrls: this.stringArray(report.post.mediaUrlsJson), createdAt: report.post.createdAt }, user: this.userView(report.post.user, await this.previousViolations(report.post.userId)), reportHistory: history.map((item) => ({ id: item.id, reason: item.reason, label: this.reasonLabel(item.reason), comment: item.comment, severity: item.severity, reportedAt: item.createdAt })) }, message: 'Social report details fetched successfully.' };
  }

  async action(user: AuthUserContext, id: string, dto: SocialModerationActionDto) {
    const report = await this.findReport(id); this.assertActionPermission(user, dto.action);
    const before = this.snapshot(report);
    const status = this.statusForAction(dto.action);
    const postData = this.postUpdateForAction(dto.action);
    const updated = await this.socialModerationRepository.runModerationAction(async (tx) => {
      const updatedPost = postData ? await this.socialModerationRepository.updateSocialPost(tx, report.postId, postData) : report.post;
      const updatedReport = await this.socialModerationRepository.updateSocialReportStatus(tx, report.id, status);
      await this.socialModerationRepository.createSocialModerationLog(tx, { socialReportId: report.id, postId: report.postId, actorId: user.uid, action: dto.action, reason: dto.reason, comment: dto.comment?.trim(), beforeJson: before, afterJson: { reportStatus: status, postStatus: updatedPost.status, postVisibility: updatedPost.visibility } });
      if (dto.action === SocialModerationAction.WARN_USER) await this.socialModerationRepository.createUserWarning(tx, { userId: report.post.userId, postId: report.postId, socialReportId: report.id, reason: dto.reason ?? report.reason, message: dto.comment?.trim() ?? 'Warning issued for community guideline violation.', issuedById: user.uid });
      if (dto.notifyUser ?? (dto.action === SocialModerationAction.HIDE || dto.action === SocialModerationAction.REMOVE || dto.action === SocialModerationAction.WARN_USER)) await this.socialModerationRepository.createNotification(tx, { recipientId: report.post.userId, recipientType: NotificationRecipientType.REGISTERED_USER, title: this.notificationTitle(dto.action), message: dto.comment?.trim() ?? this.notificationTitle(dto.action), type: 'SOCIAL_MODERATION_ACTION', metadataJson: { socialReportId: report.id, postId: report.postId, action: dto.action } });
      return { reportStatus: updatedReport.status, postStatus: updatedPost.status, postVisibility: updatedPost.visibility };
    });
    await this.auditLog.write({ actorId: user.uid, targetId: report.id, targetType: 'SOCIAL_REPORT', action: `SOCIAL_MODERATION_${dto.action}`, module: 'Social Moderation', beforeJson: before, afterJson: { reportStatus: updated.reportStatus, postStatus: updated.postStatus, postVisibility: updated.postVisibility, reason: dto.reason } });
    return { data: { id: report.id, postId: report.postId, action: dto.action, status: updated.reportStatus }, message: 'Social moderation action completed successfully.' };
  }

  async exportReports(user: AuthUserContext, query: ExportSocialReportsDto): Promise<FileResult> {
    const items = await this.socialModerationRepository.findReportsForExport({ where: this.reportWhere(query), orderBy: this.reportOrder(query.sortBy, query.sortOrder) });
    const rows = [['Report ID', 'Post ID', 'User', 'Username', 'Reason', 'Severity', 'Status', 'Report Count', 'Created At'], ...items.map((item) => [item.reportId, item.postId, this.name(item.post.user), this.username(item.post.user), item.reason, item.severity, item.status, String(item.post.reports.length), item.createdAt.toISOString()])];
    await this.auditLog.write({ actorId: user.uid, targetId: null, targetType: 'SOCIAL_MODERATION_EXPORT', action: 'SOCIAL_MODERATION_EXPORT_GENERATED', module: 'Social Moderation', afterJson: { count: items.length } });
    return this.file(rows, query.format ?? ExportFormat.CSV, 'social-moderation-log');
  }

  async ruleStats() {
    const now = new Date(); const dayStart = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate())); const monthStart = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1)); const weekAgo = new Date(now.getTime() - 7 * 86_400_000);
    const [activeRules, createdThisMonth, autoFlaggedToday, logs] = await this.socialReportingRulesRepository.findRuleStatsRows({ dayStart, monthStart, weekAgo });
    const avg = logs.length ? Math.round(logs.reduce((s, l) => s + (l.createdAt.getTime() - l.report.createdAt.getTime()) / 60000, 0) / logs.length) : 0;
    return { data: { activeRules, activeRulesDeltaText: `+${createdThisMonth} this month`, autoFlaggedToday, accuracyScore: 84, averageEscalationTimeMinutes: avg, averageEscalationDeltaText: '-4m from last week' }, message: 'Social reporting rule stats fetched successfully.' };
  }

  async rules(query: ListSocialReportingRulesDto) { const page = query.page ?? 1; const limit = Math.min(query.limit ?? 20, 100); const where = this.ruleWhere(query); const [items, total] = await this.socialReportingRulesRepository.findRulesAndCount({ where, orderBy: this.ruleOrder(query.sortBy, query.sortOrder), skip: (page - 1) * limit, take: limit }); return { data: items.map((item) => this.ruleItem(item)), meta: { page, limit, total, totalPages: Math.ceil(total / limit) }, message: 'Social reporting rules fetched successfully.' }; }
  async createRule(user: AuthUserContext, dto: CreateSocialReportingRuleDto) { const created = await this.socialReportingRulesRepository.createRule({ reportCategory: dto.reportCategory.trim(), label: dto.label.trim(), description: dto.description?.trim(), iconKey: dto.iconKey?.trim(), autoFlagThreshold: dto.autoFlagThreshold, escalationRule: dto.escalationRule, isActive: dto.isActive ?? true }); await this.auditLog.write({ actorId: user.uid, targetId: created.id, targetType: 'SOCIAL_REPORTING_RULE', action: 'SOCIAL_REPORTING_RULE_CREATED', module: 'Social Reporting Rules', afterJson: this.ruleItem(created) }); return { data: this.ruleItem(created), message: 'Social reporting rule created successfully.' }; }
  async ruleDetails(id: string) { return { data: this.ruleItem(await this.findRule(id)), message: 'Social reporting rule fetched successfully.' }; }
  async updateRule(user: AuthUserContext, id: string, dto: UpdateSocialReportingRuleDto) { const current = await this.findRule(id); const updated = await this.socialReportingRulesRepository.updateRule(id, { label: dto.label?.trim(), description: dto.description?.trim(), iconKey: dto.iconKey?.trim(), autoFlagThreshold: dto.autoFlagThreshold, escalationRule: dto.escalationRule, isActive: dto.isActive }); await this.auditLog.write({ actorId: user.uid, targetId: id, targetType: 'SOCIAL_REPORTING_RULE', action: 'SOCIAL_REPORTING_RULE_UPDATED', module: 'Social Reporting Rules', beforeJson: this.ruleItem(current), afterJson: this.ruleItem(updated) }); return { data: this.ruleItem(updated), message: 'Social reporting rule updated successfully.' }; }
  async deleteRule(user: AuthUserContext, id: string) { const current = await this.findRule(id); const deleted = await this.socialReportingRulesRepository.softDeleteRule(id); await this.auditLog.write({ actorId: user.uid, targetId: id, targetType: 'SOCIAL_REPORTING_RULE', action: 'SOCIAL_REPORTING_RULE_DELETED', module: 'Social Reporting Rules', beforeJson: this.ruleItem(current), afterJson: { deletedAt: deleted.deletedAt } }); return { data: { id, deleted: true }, message: 'Social reporting rule deleted successfully.' }; }
  async updateRuleStatus(user: AuthUserContext, id: string, dto: UpdateSocialReportingRuleStatusDto) { const current = await this.findRule(id); const updated = await this.socialReportingRulesRepository.updateRuleStatus(id, dto.isActive); await this.auditLog.write({ actorId: user.uid, targetId: id, targetType: 'SOCIAL_REPORTING_RULE', action: 'SOCIAL_REPORTING_RULE_STATUS_UPDATED', module: 'Social Reporting Rules', beforeJson: { isActive: current.isActive }, afterJson: { isActive: updated.isActive, reason: dto.reason } }); return { data: this.ruleItem(updated), message: 'Social reporting rule status updated successfully.' }; }
  async exportRules(user: AuthUserContext, query: ExportSocialRulesDto): Promise<FileResult> { const items = await this.socialReportingRulesRepository.findRulesForExport(query.isActive); await this.auditLog.write({ actorId: user.uid, targetId: null, targetType: 'SOCIAL_REPORTING_RULE_EXPORT', action: 'SOCIAL_REPORTING_RULE_EXPORT_GENERATED', module: 'Social Reporting Rules', afterJson: { count: items.length } }); return this.file([['Category', 'Label', 'Threshold', 'Escalation Rule', 'Active', 'Updated At'], ...items.map((i) => [i.reportCategory, i.label, String(i.autoFlagThreshold), i.escalationRule, String(i.isActive), i.updatedAt.toISOString()])], query.format ?? ExportFormat.CSV, 'social-reporting-rules'); }

  private reportInclude() { return SOCIAL_REPORT_INCLUDE; }
  private reportWhere(query: Partial<ListSocialReportsDto>): Prisma.SocialReportWhereInput { const reason = query.reportType && query.reportType !== AllSocialReportReason.ALL ? this.reason(query.reportType) : undefined; const status = query.status && query.status !== AllSocialReportStatus.ALL ? query.status as SocialReportStatus : undefined; const severity = query.severity && query.severity !== AllSocialSeverity.ALL ? query.severity as SocialReportSeverity : undefined; return { reason, status, severity, ...(query.fromDate || query.toDate ? { createdAt: { gte: query.fromDate ? new Date(query.fromDate) : undefined, lte: query.toDate ? new Date(query.toDate) : undefined } } : {}), ...(query.search ? { OR: [{ reportId: { contains: query.search, mode: 'insensitive' } }, { postId: { contains: query.search, mode: 'insensitive' } }, { post: { content: { contains: query.search, mode: 'insensitive' } } }, { post: { user: { firstName: { contains: query.search, mode: 'insensitive' } } } }, { post: { user: { lastName: { contains: query.search, mode: 'insensitive' } } } }] } : {}) }; }
  private dateWhere(query: SocialModerationStatsDto): Prisma.SocialReportWhereInput { const range = query.range ?? SocialRange.LAST_30_DAYS; const now = new Date(); const from = query.fromDate ? new Date(query.fromDate) : range === SocialRange.LAST_24_HOURS ? new Date(now.getTime() - 86_400_000) : range === SocialRange.LAST_7_DAYS ? new Date(now.getTime() - 7 * 86_400_000) : range === SocialRange.CUSTOM ? undefined : new Date(now.getTime() - 30 * 86_400_000); return { createdAt: { gte: from, lte: query.toDate ? new Date(query.toDate) : undefined } }; }
  private reportOrder(sortBy?: SocialSortBy, sortOrder?: SortOrder): Prisma.SocialReportOrderByWithRelationInput { const order = sortOrder === SortOrder.ASC ? 'asc' : 'desc'; if (sortBy === SocialSortBy.SEVERITY) return { severity: order }; if (sortBy === SocialSortBy.REPORT_COUNT) return { post: { reports: { _count: order } } }; return { createdAt: order }; }
  private reportListItem(item: ReportView) { const count = item.post.reports.length; return { id: item.id, reportId: item.reportId, post: { id: item.postId, previewImageUrl: this.stringArray(item.post.mediaUrlsJson)[0] ?? null, contentPreview: this.preview(item.post.content) }, user: this.userView(item.post.user, 0), reportType: item.reason, reportTypeLabel: this.reasonLabel(item.reason), reportCount: count, severity: item.severity, status: item.status, createdAt: item.createdAt }; }
  private async findReport(id: string): Promise<ReportView> { const report = await this.socialModerationRepository.findReport(id); if (!report) throw new NotFoundException('Social report not found'); return report; }
  private async previousViolations(userId: string): Promise<number> { return this.socialModerationRepository.countUserWarnings(userId); }
  private statusForAction(action: SocialModerationAction): SocialReportStatus { if (action === SocialModerationAction.HIDE) return SocialReportStatus.HIDDEN; if (action === SocialModerationAction.REMOVE) return SocialReportStatus.REMOVED; if (action === SocialModerationAction.WARN_USER) return SocialReportStatus.WARNED; if (action === SocialModerationAction.DISMISS_REPORT) return SocialReportStatus.DISMISSED; return SocialReportStatus.REVIEWED; }
  private postUpdateForAction(action: SocialModerationAction): Prisma.SocialPostUpdateInput | null { if (action === SocialModerationAction.HIDE) return { visibility: SocialPostVisibility.HIDDEN }; if (action === SocialModerationAction.REMOVE) return { status: SocialPostStatus.REMOVED }; if (action === SocialModerationAction.RESTORE) return { visibility: SocialPostVisibility.PUBLIC, status: SocialPostStatus.ACTIVE }; return null; }
  private assertActionPermission(user: AuthUserContext, action: SocialModerationAction): void { if (user.role === UserRole.SUPER_ADMIN) return; const perms = JSON.stringify(user.permissions ?? {}); if (!perms.includes('moderate')) throw new BadRequestException('Missing socialModeration.moderate permission'); if (action === SocialModerationAction.HIDE && !perms.includes('hide')) throw new BadRequestException('Missing socialModeration.hide permission'); if (action === SocialModerationAction.REMOVE && !perms.includes('remove')) throw new BadRequestException('Missing socialModeration.remove permission'); if (action === SocialModerationAction.WARN_USER && !perms.includes('warn')) throw new BadRequestException('Missing socialModeration.warn permission'); }
  private ruleWhere(query: ListSocialReportingRulesDto): Prisma.SocialReportingRuleWhereInput { return { deletedAt: null, isActive: query.isActive, reportCategory: query.reportCategory, ...(query.search ? { OR: [{ reportCategory: { contains: query.search, mode: 'insensitive' } }, { label: { contains: query.search, mode: 'insensitive' } }] } : {}) }; }
  private ruleOrder(sortBy?: RuleSortBy, sortOrder?: SortOrder): Prisma.SocialReportingRuleOrderByWithRelationInput { const order = sortOrder === SortOrder.ASC ? 'asc' : 'desc'; if (sortBy === RuleSortBy.AUTO_FLAG_THRESHOLD) return { autoFlagThreshold: order }; if (sortBy === RuleSortBy.CREATED_AT) return { createdAt: order }; return { updatedAt: order }; }
  private async findRule(id: string): Promise<RuleView> { const rule = await this.socialReportingRulesRepository.findRuleById(id); if (!rule) throw new NotFoundException('Social reporting rule not found'); return rule; }
  private ruleItem(rule: RuleView) { return { id: rule.id, reportCategory: rule.reportCategory, label: rule.label, description: rule.description, iconKey: rule.iconKey, autoFlagThreshold: rule.autoFlagThreshold, escalationRule: rule.escalationRule, escalationRuleLabel: this.escalationLabel(rule.escalationRule), lastModifiedAt: rule.updatedAt, isActive: rule.isActive }; }
  private reason(input: AllSocialReportReason): SocialReportReason { return input === AllSocialReportReason.INAPPROPRIATE ? SocialReportReason.INAPPROPRIATE : input as unknown as SocialReportReason; }
  private reasonLabel(reason: SocialReportReason): string { return reason.toLowerCase().split('_').map((p) => p[0].toUpperCase() + p.slice(1)).join(' '); }
  private escalationLabel(rule: string): string { return rule.toLowerCase().split('_').map((p) => p[0].toUpperCase() + p.slice(1)).join(' '); }
  private userView(user: { id: string; firstName: string; lastName: string; avatarUrl: string | null; createdAt: Date }, previousViolations: number) { return { id: user.id, name: this.name(user), username: `@${user.firstName.toLowerCase()}_${user.lastName.toLowerCase()}`, avatarUrl: user.avatarUrl, joinedAt: user.createdAt, previousViolations }; }
  private snapshot(report: ReportView) { return { reportStatus: report.status, postStatus: report.post.status, postVisibility: report.post.visibility }; }
  private file(rows: string[][], format: ExportFormat, name: string): FileResult { const content = rows.map((row) => row.map((cell) => `"${cell.replaceAll('"', '""')}"`).join(',')).join('\n'); return { content, filename: `${name}.${format === ExportFormat.PDF ? 'pdf' : 'csv'}`, contentType: format === ExportFormat.PDF ? 'application/pdf' : 'text/csv' }; }
  private notificationTitle(action: SocialModerationAction): string { if (action === SocialModerationAction.HIDE) return 'Your post was hidden'; if (action === SocialModerationAction.REMOVE) return 'Your post was removed'; if (action === SocialModerationAction.WARN_USER) return 'Community guideline warning'; return 'Social moderation update'; }
  private stringArray(value: Prisma.JsonValue): string[] { return Array.isArray(value) ? value.filter((item): item is string => typeof item === 'string') : []; }
  private preview(text: string): string { return text.length > 72 ? `${text.slice(0, 69)}...` : text; }
  private name(user: { firstName: string; lastName: string }): string { return `${user.firstName} ${user.lastName}`.trim(); }
  private username(user: { firstName: string; lastName: string }): string { return `@${user.firstName.toLowerCase()}_${user.lastName.toLowerCase()}`; }
}
