import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { NotificationDevicePlatform } from '@prisma/client';
import { Type } from 'class-transformer';
import { IsBoolean, IsEnum, IsInt, IsObject, IsOptional, IsString, Min } from 'class-validator';

export enum SortOrder { ASC = 'ASC', DESC = 'DESC' }
export enum NotificationTypeDto { BIRTHDAY_REMINDER = 'BIRTHDAY_REMINDER', GIFT_DELIVERED = 'GIFT_DELIVERED', NEW_CONTACT_AVAILABLE = 'NEW_CONTACT_AVAILABLE', PROMOTIONAL = 'PROMOTIONAL', BROADCAST = 'BROADCAST', SYSTEM = 'SYSTEM', SECURITY = 'SECURITY', ORDER = 'ORDER' }
export enum NotificationFilterDto { ALL = 'ALL', UNREAD = 'UNREAD', BIRTHDAYS = 'BIRTHDAYS', DELIVERIES = 'DELIVERIES', NEW_CONTACTS = 'NEW_CONTACTS' }
export enum NotificationActionDto { SEND_GIFT = 'SEND_GIFT', REMIND_ME_LATER = 'REMIND_ME_LATER', VIEW_ORDER = 'VIEW_ORDER', VIEW_CONTACT = 'VIEW_CONTACT' }

export class ListNotificationsDto { @ApiPropertyOptional({ example: 1 }) @IsOptional() @Type(() => Number) @IsInt() @Min(1) page?: number; @ApiPropertyOptional({ example: 10, default: 10 }) @IsOptional() @Type(() => Number) @IsInt() @Min(1) limit?: number; @ApiPropertyOptional({ enum: NotificationFilterDto, example: NotificationFilterDto.UNREAD }) @IsOptional() @IsEnum(NotificationFilterDto) filter?: NotificationFilterDto; @ApiPropertyOptional({ enum: NotificationTypeDto, example: NotificationTypeDto.ORDER }) @IsOptional() @IsEnum(NotificationTypeDto) type?: NotificationTypeDto; @ApiPropertyOptional({ example: false }) @IsOptional() @Type(() => Boolean) @IsBoolean() isRead?: boolean; @ApiPropertyOptional({ example: true }) @IsOptional() @Type(() => Boolean) @IsBoolean() groupByDate?: boolean; @ApiPropertyOptional({ enum: SortOrder, example: SortOrder.DESC }) @IsOptional() @IsEnum(SortOrder) sortOrder?: SortOrder; }
export class DeviceTokenDto { @ApiProperty({ example: 'ExponentPushToken[xxxxxxxxxxxxxxxxxxxxxx]' }) @IsString() token!: string; @ApiProperty({ enum: NotificationDevicePlatform, example: NotificationDevicePlatform.IOS }) @IsEnum(NotificationDevicePlatform) platform!: NotificationDevicePlatform; @ApiProperty({ example: 'ios-iphone-15-pro-device-id' }) @IsString() deviceId!: string; }
export class NotificationActionRequestDto { @ApiProperty({ enum: NotificationActionDto, example: NotificationActionDto.SEND_GIFT }) @IsEnum(NotificationActionDto) action!: NotificationActionDto; }
export class UpdateNotificationPreferencesDto { @ApiPropertyOptional({ example: true }) @IsOptional() @IsBoolean() pushEnabled?: boolean; @ApiPropertyOptional({ example: true }) @IsOptional() @IsBoolean() emailEnabled?: boolean; @ApiPropertyOptional({ example: false }) @IsOptional() @IsBoolean() smsEnabled?: boolean; @ApiPropertyOptional({ example: true }) @IsOptional() @IsBoolean() dealUpdatesEnabled?: boolean; @ApiPropertyOptional({ example: true }) @IsOptional() @IsBoolean() birthdayRemindersEnabled?: boolean; @ApiPropertyOptional({ example: true }) @IsOptional() @IsBoolean() deliveryUpdatesEnabled?: boolean; @ApiPropertyOptional({ example: true }) @IsOptional() @IsBoolean() newContactAlertsEnabled?: boolean; @ApiPropertyOptional({ example: { newOrders: true, orderCancellations: true, orderDelays: false } }) @IsOptional() @IsObject() providerOrderAlerts?: Record<string, boolean>; @ApiPropertyOptional({ example: { securityAlerts: true, loginFromNewDevice: true } }) @IsOptional() @IsObject() providerAccountActivity?: Record<string, boolean>; @ApiPropertyOptional({ example: { weeklyPerformanceSummary: true, newFeatureAnnouncements: false, promotionalOffers: false } }) @IsOptional() @IsObject() providerMarketingUpdates?: Record<string, boolean>; }
