import { BadRequestException, ForbiddenException } from '@nestjs/common';
import { ChatMessageType, SupportChatParticipantType, SupportChatSenderType, SupportChatStatus, UserRole } from '@prisma/client';
import { readFileSync } from 'fs';
import { join } from 'path';
import { SupportChatParticipantFilter } from '../dto/support-chat.dto';
import { SupportChatRepository } from '../repositories/support-chat.repository';
import { SupportChatService } from '../services/support-chat.service';
const now=new Date('2026-05-16T10:00:00.000Z');
const provider={id:'provider_1',role:UserRole.PROVIDER,firstName:'Luxe',lastName:'Unboxed',providerBusinessName:'Luxe Unboxed',avatarUrl:'https://cdn.example.com/avatar.png'};
const admin={uid:'admin_1',role:UserRole.ADMIN,permissions:{supportChats:['read','reply','resolve']}};
const superAdmin={uid:'super_1',role:UserRole.SUPER_ADMIN};
const chat={id:'support_chat_1',participantId:'provider_1',participantType:SupportChatParticipantType.PROVIDER,subject:'Support Ticket',status:SupportChatStatus.ACTIVE,assignedAdminId:'admin_1',lastMessageId:'msg_1',lastMessageAt:now,participantUnreadCount:0,adminUnreadCount:2,resolvedAt:null,resolvedById:null,createdAt:now,updatedAt:now,participant:provider,assignedAdmin:{id:'admin_1',firstName:'Alex',lastName:'Rivera'},lastMessage:{id:'msg_1',body:"I've attached the new listing...",createdAt:now}};
function createService(){const repo={findChats:jest.fn().mockResolvedValue([chat]),countChats:jest.fn().mockResolvedValue(1),findChatById:jest.fn().mockResolvedValue(chat),findChatForParticipant:jest.fn().mockResolvedValue(chat),findMessages:jest.fn().mockResolvedValue([{id:'msg_1',senderId:'provider_1',senderType:SupportChatSenderType.PARTICIPANT,messageType:ChatMessageType.TEXT,body:'Help',attachmentUrlsJson:['https://cdn.example.com/a.png'],createdAt:now,sender:provider}]),createChat:jest.fn().mockResolvedValue(chat),createAdminMessage:jest.fn().mockResolvedValue({id:'msg_2',messageType:ChatMessageType.TEXT,body:'I am checking this issue now.'}),createParticipantMessage:jest.fn().mockResolvedValue({id:'msg_3',messageType:ChatMessageType.TEXT,body:'Help',clientMessageId:null}),markRead:jest.fn().mockResolvedValue({...chat,adminUnreadCount:0}),markParticipantRead:jest.fn().mockResolvedValue({...chat,participantUnreadCount:0}),resolve:jest.fn().mockResolvedValue({...chat,status:SupportChatStatus.RESOLVED}),reopen:jest.fn().mockResolvedValue({...chat,status:SupportChatStatus.ACTIVE}),createNotification:jest.fn().mockResolvedValue({}),findCompletedUploadsByUrls:jest.fn().mockResolvedValue([{fileUrl:'https://cdn.example.com/support.png'}])};return{service:new SupportChatService(repo as unknown as SupportChatRepository),repo};}
describe('SupportChatService',()=>{
 it('lists assigned chats for admin and all chats for super admin',async()=>{const{service,repo}=createService();const res=await service.list(admin,{participantType:SupportChatParticipantFilter.PROVIDER,unreadOnly:true});expect(res.data[0]).toMatchObject({id:'support_chat_1',participant:{type:'PROVIDER',name:'Luxe Unboxed'},unreadCount:2,status:'ACTIVE'});expect((repo.findChats.mock.calls as unknown[][])[0]?.[0]).toMatchObject({where:{assignedAdminId:'admin_1',participantType:'PROVIDER',adminUnreadCount:{gt:0}}});await service.list(superAdmin,{});expect((repo.findChats.mock.calls as unknown[][])[1]?.[0]).toMatchObject({where:{}});});
 it('returns detail messages scoped to support chat',async()=>{const{service,repo}=createService();const res=await service.details(admin,'support_chat_1');expect(res.data.messages[0]).toMatchObject({body:'Help',attachmentUrls:['https://cdn.example.com/a.png']});expect(repo.findMessages).toHaveBeenCalledWith('support_chat_1');});
 it('replies with support-chat attachment URLs and notifies participant',async()=>{const{service,repo}=createService();const res=await service.reply(admin,'support_chat_1',{messageType:ChatMessageType.TEXT,body:'I am checking this issue now.',attachmentUrls:['https://cdn.example.com/support.png']});expect(res.data).toMatchObject({id:'msg_2',supportChatId:'support_chat_1'});expect(repo.findCompletedUploadsByUrls).toHaveBeenCalledWith(['https://cdn.example.com/support.png']);expect(repo.createNotification).toHaveBeenCalledWith(expect.objectContaining({recipientId:'provider_1',type:'SUPPORT_CHAT_REPLY'}));});
 it('allows participants to create support chats, reply, and mark their thread read',async()=>{const{service,repo}=createService();const providerUser={uid:'provider_1',role:UserRole.PROVIDER};await service.createForCurrentParticipant(providerUser,{subject:'Need help',initialMessage:'Help',attachmentUrls:['https://cdn.example.com/support.png']});await service.participantReply(providerUser,'support_chat_1',{messageType:ChatMessageType.TEXT,body:'Help',attachmentUrls:['https://cdn.example.com/support.png']});await service.markParticipantRead(providerUser,'support_chat_1');expect(repo.createChat).toHaveBeenCalledWith(expect.objectContaining({participantId:'provider_1',participantType:SupportChatParticipantType.PROVIDER}));expect(repo.createParticipantMessage).toHaveBeenCalled();expect(repo.markParticipantRead).toHaveBeenCalledWith('support_chat_1');});
 it('rejects attachments outside completed support-chat uploads',async()=>{const{service,repo}=createService();repo.findCompletedUploadsByUrls.mockResolvedValueOnce([]);await expect(service.reply(admin,'support_chat_1',{messageType:ChatMessageType.TEXT,body:'x',attachmentUrls:['https://cdn.example.com/bad.png']})).rejects.toBeInstanceOf(BadRequestException);});
 it('marks read resolves and reopens with notifications',async()=>{const{service,repo}=createService();await expect(service.markRead(admin,'support_chat_1')).resolves.toMatchObject({data:{unreadCount:0}});await service.resolve(admin,'support_chat_1',{comment:'Done',notifyParticipant:true});await service.reopen(admin,'support_chat_1',{comment:'Reopened',notifyParticipant:true});expect(repo.resolve).toHaveBeenCalledWith('support_chat_1','admin_1');expect(repo.reopen).toHaveBeenCalledWith('support_chat_1');expect(repo.createNotification).toHaveBeenCalledWith(expect.objectContaining({type:'SUPPORT_CHAT_RESOLVED'}));expect(repo.createNotification).toHaveBeenCalledWith(expect.objectContaining({type:'SUPPORT_CHAT_REOPENED'}));});
 it('blocks unassigned admin without read.all',async()=>{const{service,repo}=createService();repo.findChatById.mockResolvedValueOnce({...chat,assignedAdminId:'other_admin'});await expect(service.details(admin,'support_chat_1')).rejects.toBeInstanceOf(ForbiddenException);});
 it('returns stats',async()=>{const{service,repo}=createService();repo.countChats.mockResolvedValueOnce(7).mockResolvedValueOnce(2).mockResolvedValueOnce(3).mockResolvedValueOnce(1).mockResolvedValueOnce(4);await expect(service.stats(admin)).resolves.toMatchObject({data:{total:7,open:2,active:3,resolved:1,unread:4}});});
});
describe('Support chat API stability',()=>{const chatsController=readFileSync(join(__dirname,'../../chats/chats.controller.ts'),'utf8');const moduleFile=readFileSync(join(__dirname,'../support-chat.module.ts'),'utf8');const schema=readFileSync(join(__dirname,'../../../../prisma/schema.prisma'),'utf8');const permissions=readFileSync(join(__dirname,'../../admin-roles/constants/permission-catalog.ts'),'utf8');const storage=readFileSync(join(__dirname,'../../storage/dto/create-presigned-upload.dto.ts'),'utf8');const main=readFileSync(join(__dirname,'../../../main.ts'),'utf8');it('keeps support chat persistence behind unified routes',()=>{expect(schema).toContain('model SupportChat');expect(schema).toContain('model SupportChatMessage');expect(schema).toContain('model ChatThread');expect(moduleFile).not.toContain('SupportChatController');expect(chatsController).toContain("@ApiTags('08 Chat - Unified Threads')");for(const route of ["@Get()","@Get('threads/:threadId')","@Post('threads/:threadId/messages')","@Patch('threads/:threadId/read')","@Post('threads/:threadId/resolve')","@Post('threads/:threadId/reopen')","@Get('threads/:threadId/audit-log')"])expect(chatsController).toContain(route);expect(permissions).toContain("module: 'supportChats'");expect(storage).toContain('SUPPORT_CHAT_ATTACHMENTS');expect(main).not.toContain("'02 Admin - Support Chat'");expect(main).toContain("'08 Chat - Unified Threads'");});});
