import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { IsBoolean, IsEmail, IsISO4217CurrencyCode, IsISO8601, IsInt, IsNumber, IsOptional, IsString, IsUrl, Max, MaxLength, Min, ValidateNested } from 'class-validator';

export class PasswordPolicyDto { @ApiProperty({ example: 8 }) @Type(() => Number) @IsInt() @Min(8) @Max(128) minLength!: number; @ApiProperty({ example: true }) @IsBoolean() requireUppercase!: boolean; @ApiProperty({ example: true }) @IsBoolean() requireLowercase!: boolean; @ApiProperty({ example: true }) @IsBoolean() requireNumber!: boolean; @ApiProperty({ example: true }) @IsBoolean() requireSymbol!: boolean; }
export class PlatformInfoDto { @ApiProperty({ example: 'Gift App' }) @IsString() @MaxLength(80) applicationName!: string; @ApiProperty({ example: 'support@giftapp.com' }) @IsEmail() supportEmail!: string; @ApiPropertyOptional({ example: 'https://cdn.example.com/logo.png' }) @IsOptional() @IsUrl() platformLogoUrl?: string; }
export class SecuritySettingsDto { @ApiProperty({ example: 30 }) @Type(() => Number) @IsInt() @Min(5) @Max(1440) sessionTimeoutMinutes!: number; @ApiProperty({ example: true }) @IsBoolean() adminMfaRequired!: boolean; @ApiProperty({ type: PasswordPolicyDto }) @ValidateNested() @Type(() => PasswordPolicyDto) passwordPolicy!: PasswordPolicyDto; }
export class PaymentSettingsDto { @ApiProperty({ example: 'USD' }) @IsISO4217CurrencyCode() defaultCurrency!: string; @ApiProperty({ example: 2.5 }) @Type(() => Number) @IsNumber() @Min(0) @Max(100) transactionFeePercent!: number; }
export class NotificationSettingsDto { @ApiProperty({ example: true }) @IsBoolean() pushNotificationsEnabled!: boolean; @ApiProperty({ example: true }) @IsBoolean() emailNotificationsEnabled!: boolean; }
export class UpdateSystemSettingsDto { @ApiProperty({ type: PlatformInfoDto }) @ValidateNested() @Type(() => PlatformInfoDto) platformInfo!: PlatformInfoDto; @ApiProperty({ type: SecuritySettingsDto }) @ValidateNested() @Type(() => SecuritySettingsDto) security!: SecuritySettingsDto; @ApiProperty({ type: PaymentSettingsDto }) @ValidateNested() @Type(() => PaymentSettingsDto) payments!: PaymentSettingsDto; @ApiProperty({ type: NotificationSettingsDto }) @ValidateNested() @Type(() => NotificationSettingsDto) notifications!: NotificationSettingsDto; }
export class UpdateLogoDto { @ApiProperty({ example: 'https://cdn.example.com/logo.png' }) @IsUrl() platformLogoUrl!: string; @ApiPropertyOptional({ example: 'upload_id' }) @IsOptional() @IsString() uploadId?: string; }
export class SmtpTestDto { @ApiProperty({ example: 'admin@giftapp.com' }) @IsEmail() to!: string; }
export class ListSystemSettingsAuditLogsDto { @ApiPropertyOptional({ example: 1 }) @IsOptional() @Type(() => Number) @IsInt() @Min(1) page?: number; @ApiPropertyOptional({ example: 20 }) @IsOptional() @Type(() => Number) @IsInt() @Min(1) @Max(100) limit?: number; @ApiPropertyOptional() @IsOptional() @IsISO8601() fromDate?: string; @ApiPropertyOptional() @IsOptional() @IsISO8601() toDate?: string; }
