import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { NotificationRecipientType, Prisma, SupportChatParticipantType, SupportChatStatus, UserRole } from '@prisma/client';
import { AuthUserContext } from '../../../common/decorators/current-user.decorator';
import { ResolveSupportChatDto, SendSupportChatMessageDto, ListSupportChatsDto, SupportChatParticipantFilter, SupportChatStatusFilter } from '../dto/support-chat.dto';
import { SUPPORT_CHAT_INCLUDE, SupportChatRepository } from '../repositories/support-chat.repository';
type Chat = Prisma.SupportChatGetPayload<{ include: typeof SUPPORT_CHAT_INCLUDE }>;
@Injectable()
export class SupportChatService { constructor(private readonly repo: SupportChatRepository) {}
  async list(user: AuthUserContext, q: ListSupportChatsDto) { const page=q.page??1, limit=Math.min(q.limit??20,100); const where=this.where(user,q); const [items,total]=await Promise.all([this.repo.findChats({ where, include: SUPPORT_CHAT_INCLUDE, orderBy:{ updatedAt:'desc'}, skip:(page-1)*limit, take:limit }), this.repo.countChats(where)]); return { data: items.map((c)=>this.toList(c)), meta:{page,limit,total,totalPages:Math.ceil(total/limit)}, message:'Support chats fetched successfully.'}; }
  async details(user: AuthUserContext,id:string){ const chat=await this.getAllowed(user,id); const messages=await this.repo.findMessages(id); return { data:{...this.toList(chat), assignedAdmin:chat.assignedAdmin?{id:chat.assignedAdmin.id,name:this.name(chat.assignedAdmin)}:null, messages:messages.map((m)=>({id:m.id,sender:{id:m.sender.id,type:m.senderType,name:this.participantName(m.sender),avatarUrl:m.sender.avatarUrl},messageType:m.messageType,body:m.body,attachmentUrls:this.urls(m.attachmentUrlsJson),createdAt:m.createdAt}))}, message:'Support chat fetched successfully.'}; }
  async reply(user:AuthUserContext,id:string,dto:SendSupportChatMessageDto){ const chat=await this.getAllowed(user,id); this.assertCan(user,'supportChats.reply'); await this.assertAttachments(dto.attachmentUrls); const msg=await this.repo.createAdminMessage({supportChatId:id,senderId:user.uid,messageType:dto.messageType,body:dto.body,attachmentUrls:dto.attachmentUrls}); await this.notify(chat,'Support reply received',dto.body??'You received a support reply.','SUPPORT_CHAT_REPLY'); return { data:{id:msg.id,supportChatId:id,messageType:msg.messageType,body:msg.body,attachmentUrls:dto.attachmentUrls}, message:'Support chat message sent successfully.'}; }
  async markRead(user:AuthUserContext,id:string){ await this.getAllowed(user,id); await this.repo.markRead(id); return { data:{id,unreadCount:0}, message:'Support chat marked as read.'}; }
  async resolve(user:AuthUserContext,id:string,dto:ResolveSupportChatDto){ const chat=await this.getAllowed(user,id); this.assertCan(user,'supportChats.resolve'); const updated=await this.repo.resolve(id,user.uid); if(dto.notifyParticipant??true) await this.notify(chat,'Support ticket resolved',dto.comment??'Your support ticket has been resolved.','SUPPORT_CHAT_RESOLVED'); return { data:{id:updated.id,status:updated.status}, message:'Support chat resolved successfully.'}; }
  async reopen(user:AuthUserContext,id:string,dto:ResolveSupportChatDto){ const chat=await this.getAllowed(user,id); this.assertCan(user,'supportChats.resolve'); const updated=await this.repo.reopen(id); if(dto.notifyParticipant??true) await this.notify(chat,'Support ticket reopened',dto.comment??'Your support ticket has been reopened.','SUPPORT_CHAT_REOPENED'); return { data:{id:updated.id,status:updated.status}, message:'Support chat reopened successfully.'}; }
  async stats(user:AuthUserContext){ const where=this.where(user,{}); const [total,open,active,resolved,unread]=await Promise.all([this.repo.countChats(where),this.repo.countChats({...where,status:SupportChatStatus.OPEN}),this.repo.countChats({...where,status:SupportChatStatus.ACTIVE}),this.repo.countChats({...where,status:SupportChatStatus.RESOLVED}),this.repo.countChats({...where,adminUnreadCount:{gt:0}})]); return { data:{total,open,active,resolved,unread}, message:'Support chat stats fetched successfully.'}; }
  private where(user:AuthUserContext,q:ListSupportChatsDto):Prisma.SupportChatWhereInput{ const base:Prisma.SupportChatWhereInput={}; if(user.role===UserRole.ADMIN&&!this.has(user,'supportChats.read.all')) base.assignedAdminId=user.uid; if(q.participantType&&q.participantType!==SupportChatParticipantFilter.ALL) base.participantType=q.participantType; if(q.status&&q.status!==SupportChatStatusFilter.ALL) base.status=q.status; if(q.unreadOnly) base.adminUnreadCount={gt:0}; if(q.search?.trim()) base.OR=[{subject:{contains:q.search,mode:'insensitive'}},{participant:{firstName:{contains:q.search,mode:'insensitive'}}},{participant:{lastName:{contains:q.search,mode:'insensitive'}}},{participant:{providerBusinessName:{contains:q.search,mode:'insensitive'}}}]; return base; }
  private async getAllowed(user:AuthUserContext,id:string):Promise<Chat>{ const chat=await this.repo.findChatById(id); if(!chat) throw new NotFoundException('Support chat not found'); if(user.role===UserRole.ADMIN&&!this.has(user,'supportChats.read.all')&&chat.assignedAdminId!==user.uid) throw new ForbiddenException('You can view only assigned support chats'); return chat; }
  private assertCan(user:AuthUserContext,permission:string){ if(user.role===UserRole.SUPER_ADMIN)return; if(!this.has(user,permission)) throw new ForbiddenException('Your role does not have the required permission'); }
  private async assertAttachments(urls:string[]){ if(!urls.length)return; const rows=await this.repo.findCompletedUploadsByUrls(urls); const found=new Set(rows.map(r=>r.fileUrl)); const missing=urls.filter(u=>!found.has(u)); if(missing.length) throw new BadRequestException('Attachments must use completed support-chat-attachments uploads'); }
  private has(user:AuthUserContext,permission:string){ if(user.role===UserRole.SUPER_ADMIN)return true; if(!user.permissions||typeof user.permissions!=='object'||Array.isArray(user.permissions))return false; const dot=permission.indexOf('.'); const module=permission.slice(0,dot); const key=permission.slice(dot+1); const values=(user.permissions as Record<string,unknown>)[module]; return Array.isArray(values)&&values.includes(key); }
  private toList(c:Chat){return {id:c.id,participant:{id:c.participant.id,type:c.participantType,name:this.participantName(c.participant),avatarUrl:c.participant.avatarUrl},subject:c.subject,lastMessage:c.lastMessage?.body??null,lastMessageAt:c.lastMessageAt,unreadCount:c.adminUnreadCount,status:c.status};}
  private async notify(c:Chat,title:string,message:string,type:string){ await this.repo.createNotification({recipientId:c.participantId,recipientType:c.participantType===SupportChatParticipantType.PROVIDER?NotificationRecipientType.PROVIDER:NotificationRecipientType.REGISTERED_USER,title,message,type,metadataJson:{supportChatId:c.id}}); }
  private participantName(u:{firstName:string;lastName:string;providerBusinessName?:string|null}){return u.providerBusinessName??this.name(u);} private name(u:{firstName:string;lastName:string}){return `${u.firstName} ${u.lastName}`.trim();} private urls(v:Prisma.JsonValue):string[]{return Array.isArray(v)?v.filter((x):x is string=>typeof x==='string'):[];}
}
