/* eslint-disable @typescript-eslint/require-await, @typescript-eslint/no-unsafe-return */
import { BadRequestException, NotFoundException } from '@nestjs/common';
import { PaymentMethod, PaymentStatus, ProviderOrderStatus, RefundRejectReason, RefundRequestStatus, UserRole } from '@prisma/client';
import { readFileSync } from 'fs';
import { join } from 'path';
import { ProviderRefundRequestsRepository } from '../repositories/provider-refund-requests.repository';
import { ProviderRefundRequestsService } from '../services/provider-refund-requests.service';

const user = { uid: 'provider_1', role: UserRole.PROVIDER };
const refund = { id: 'refund_1', orderId: 'order_1', providerOrderId: 'po_1', userId: 'customer_1', providerId: 'provider_1', paymentId: 'payment_1', requestedAmount: 45, approvedAmount: null, currency: 'PKR', customerReason: 'Damaged', evidenceUrlsJson: [{ type: 'IMAGE', url: 'https://cdn/refund.png' }], status: RefundRequestStatus.REQUESTED, rejectionReason: null, providerComment: null, stripeRefundId: null, transactionId: null, requestedAt: new Date(), approvedAt: null, rejectedAt: null, refundedAt: null, createdAt: new Date(), updatedAt: new Date(), user: { id: 'customer_1', firstName: 'Jane', lastName: 'Cooper', email: 'jane@example.com', avatarUrl: null }, order: { id: 'order_1', orderNumber: '88417', createdAt: new Date(), paymentStatus: PaymentStatus.SUCCEEDED }, providerOrder: { id: 'po_1', providerId: 'provider_1', orderNumber: '88417', status: ProviderOrderStatus.DELIVERED, subtotal: 40, tax: 5, total: 45, currency: 'PKR', order: { id: 'order_1', orderNumber: '88417' }, items: [{ orderItemId: 'item_1', nameSnapshot: 'Premium Cotton T-Shirt', variantNameSnapshot: 'Color: Navy, Size: M', quantity: 1, total: 25, imageUrl: 'https://cdn/item.png' }] }, payment: { id: 'payment_1', paymentMethod: PaymentMethod.STRIPE_CARD, status: PaymentStatus.SUCCEEDED, providerPaymentIntentId: 'pi_123' } };

function prismaMock(overrides: Record<string, unknown> = {}) { return { $transaction: jest.fn(async (arg: unknown) => Array.isArray(arg) ? Promise.all(arg) : (arg as (tx: unknown) => unknown)({ refundRequest: { update: jest.fn(async ({ data }) => ({ ...refund, ...data })) }, providerOrderTimeline: { create: jest.fn() }, providerOrder: { update: jest.fn() }, order: { update: jest.fn() }, payment: { update: jest.fn() }, notification: { create: jest.fn() } })), refundRequest: { findMany: jest.fn(async () => []), count: jest.fn(async () => 1), findFirst: jest.fn(async () => refund) }, ...overrides }; }

describe('ProviderRefundRequestsService', () => {
  it('provider can list own refund requests', async () => { const prisma = prismaMock({ refundRequest: { findMany: jest.fn(async () => [refund]), count: jest.fn(async () => 1), findFirst: jest.fn(async () => refund) } }); const service = new ProviderRefundRequestsService(new ProviderRefundRequestsRepository(prisma as never)); const result = await service.list(user, {}); expect(prisma.refundRequest.findMany).toHaveBeenCalledWith(expect.objectContaining({ where: { providerId: 'provider_1' } })); expect(result.data[0]).toEqual(expect.objectContaining({ id: 'refund_1', providerOrderId: 'po_1' })); });
  it('provider cannot fetch another provider refund request', async () => { const service = new ProviderRefundRequestsService(new ProviderRefundRequestsRepository(prismaMock({ refundRequest: { findFirst: jest.fn(async () => null) } }) as never)); await expect(service.details(user, 'refund_other')).rejects.toThrow(NotFoundException); });
  it('provider can fetch own refund request details', async () => { const service = new ProviderRefundRequestsService(new ProviderRefundRequestsRepository(prismaMock() as never)); const result = await service.details(user, 'refund_1'); expect(result.data).toEqual(expect.objectContaining({ id: 'refund_1', orderNumber: '88417', status: RefundRequestStatus.REQUESTED })); });
  it('provider can approve own requested refund and creates transaction marker', async () => { const service = new ProviderRefundRequestsService(new ProviderRefundRequestsRepository(prismaMock() as never)); const result = await service.approve(user, 'refund_1', { refundAmount: 45, notifyCustomer: true }); expect(result.data).toEqual(expect.objectContaining({ status: RefundRequestStatus.REFUNDED, transactionId: 'RF-REFUND_1' })); });
  it('provider cannot approve already rejected/refunded request', async () => { const service = new ProviderRefundRequestsService(new ProviderRefundRequestsRepository(prismaMock({ refundRequest: { findFirst: jest.fn(async () => ({ ...refund, status: RefundRequestStatus.REJECTED })) } }) as never)); await expect(service.approve(user, 'refund_1', { refundAmount: 10 })).rejects.toThrow(BadRequestException); });
  it('approve validates refundable amount', async () => { const service = new ProviderRefundRequestsService(new ProviderRefundRequestsRepository(prismaMock() as never)); await expect(service.approve(user, 'refund_1', { refundAmount: 46 })).rejects.toThrow(BadRequestException); });
  it('provider can reject own requested refund', async () => { const service = new ProviderRefundRequestsService(new ProviderRefundRequestsRepository(prismaMock() as never)); const result = await service.reject(user, 'refund_1', { reason: RefundRejectReason.REFUND_WINDOW_EXPIRED, notifyCustomer: true }); expect(result.data).toEqual(expect.objectContaining({ status: RefundRequestStatus.REJECTED, rejectionReason: RefundRejectReason.REFUND_WINDOW_EXPIRED })); });
  it('reject DTO requires reason and static routes do not conflict with :id', () => { const controller = readFileSync(join(__dirname, '../controllers/provider-refund-requests.controller.ts'), 'utf8'); const dto = readFileSync(join(__dirname, '../dto/provider-refund-requests.dto.ts'), 'utf8'); expect(dto).toContain('reason!: RefundRejectReason'); expect(dto).toContain('@IsEnum(RefundRejectReason)'); expect(controller.indexOf("@Get('summary')")).toBeLessThan(controller.indexOf("@Get(':id')")); expect(controller.indexOf("@Get('reject-reasons')")).toBeLessThan(controller.indexOf("@Get(':id')")); });
  it('source enforces provider ownership, notifications, and no raw payment secrets', () => { const service = readFileSync(join(__dirname, '../services/provider-refund-requests.service.ts'), 'utf8'); const repository = readFileSync(join(__dirname, '../repositories/provider-refund-requests.repository.ts'), 'utf8'); const schema = readFileSync(join(__dirname, '../../../../prisma/schema.prisma'), 'utf8'); expect(schema).toContain('model RefundRequest'); expect(repository).toContain('where: { id, providerId }'); expect(repository).toContain('CUSTOMER_REFUND_PROCESSED'); expect(repository).toContain('CUSTOMER_REFUND_REJECTED'); expect(service).not.toContain('clientSecret'); });
});
