import { Body, Controller, Delete, Get, Param, Post, Query, UseGuards } from '@nestjs/common';
import { ApiBearerAuth, ApiBody, ApiOperation, ApiTags } from '@nestjs/swagger';
import { UserRole } from '@prisma/client';
import { CurrentUser, AuthUserContext } from '../../../common/decorators/current-user.decorator';
import { Roles } from '../../../common/decorators/roles.decorator';
import { JwtAuthGuard } from '../../../common/guards/jwt-auth.guard';
import { RolesGuard } from '../../../common/guards/roles.guard';
import { CreateUserReportDto, ListBlockedUsersDto, ListUserReportsDto } from '../dto/user-safety.dto';
import { UserSafetyService } from '../services/user-safety.service';
@ApiTags('05 Customer - User Safety') @ApiBearerAuth() @UseGuards(JwtAuthGuard, RolesGuard) @Roles(UserRole.REGISTERED_USER) @Controller('customer')
export class UserSafetyController { constructor(private readonly service: UserSafetyService) {} @Get('user-report-reasons') @ApiOperation({ summary: 'Fetch generic user report reasons' }) reasons() { return this.service.reportReasons(); } @Post('users/:userId/reports') @ApiOperation({ summary: 'Report another user' }) @ApiBody({ type: CreateUserReportDto }) report(@CurrentUser() user: AuthUserContext, @Param('userId') userId: string, @Body() dto: CreateUserReportDto) { return this.service.reportUser(user, userId, dto); } @Get('user-reports') @ApiOperation({ summary: 'List own user safety reports' }) reports(@CurrentUser() user: AuthUserContext, @Query() query: ListUserReportsDto) { return this.service.reportsList(user, query); } @Get('user-reports/:id') @ApiOperation({ summary: 'Fetch own user safety report detail' }) reportDetail(@CurrentUser() user: AuthUserContext, @Param('id') id: string) { return this.service.reportDetails(user, id); } @Get('blocked-users') @ApiOperation({ summary: 'List blocked users' }) blocked(@CurrentUser() user: AuthUserContext, @Query() query: ListBlockedUsersDto) { return this.service.blockedUsers(user, query); } @Post('blocked-users/:userId') @ApiOperation({ summary: 'Block another user' }) block(@CurrentUser() user: AuthUserContext, @Param('userId') userId: string) { return this.service.blockUser(user, userId); } @Delete('blocked-users/:userId') @ApiOperation({ summary: 'Unblock user', description: 'No request body. Removes only the current customer block row.' }) unblock(@CurrentUser() user: AuthUserContext, @Param('userId') userId: string) { return this.service.unblockUser(user, userId); } }
