import { Body, Controller, Get, Param, Post, Query, StreamableFile, UseGuards } from '@nestjs/common';
import { ApiBearerAuth, ApiBody, ApiOperation, ApiResponse, ApiTags } from '@nestjs/swagger';
import { UserRole } from '@prisma/client';
import { AuthUserContext, CurrentUser } from '../../../common/decorators/current-user.decorator';
import { Permissions } from '../../../common/decorators/permissions.decorator';
import { Roles } from '../../../common/decorators/roles.decorator';
import { JwtAuthGuard } from '../../../common/guards/jwt-auth.guard';
import { PermissionsGuard } from '../../../common/guards/permissions.guard';
import { RolesGuard } from '../../../common/guards/roles.guard';
import { ListAdminUserSafetyReportsDto, UserSafetyAdminActionDto } from '../dto/user-safety.dto';
import { UserSafetyAdminService } from '../services/user-safety-admin.service';
@ApiTags('02 Admin - User Safety Moderation') @ApiBearerAuth() @UseGuards(JwtAuthGuard, RolesGuard, PermissionsGuard) @Roles(UserRole.SUPER_ADMIN, UserRole.ADMIN) @Controller('admin/user-safety')
export class UserSafetyAdminController { constructor(private readonly service: UserSafetyAdminService) {} @Get('reports') @Permissions('userSafety.read') @ApiOperation({ summary: 'List user safety reports' }) reports(@Query() query: ListAdminUserSafetyReportsDto) { return this.service.reports(query); } @Get('reports/export') @Permissions('userSafety.export') @ApiOperation({ summary: 'Export user safety reports' }) export(@CurrentUser() user: AuthUserContext, @Query() query: ListAdminUserSafetyReportsDto): Promise<StreamableFile> { return this.service.export(user, query); } @Get('reports/:id') @Permissions('userSafety.read') @ApiOperation({ summary: 'Fetch user safety report detail' }) detail(@Param('id') id: string) { return this.service.details(id); } @Post('reports/:id/action') @Permissions('userSafety.moderate') @ApiOperation({ summary: 'Moderate user safety report', description: "SUPER_ADMIN or ADMIN with userSafety.moderate. MARK_REVIEWED records review completion; WARN_REPORTED_USER warns the reported user; SUSPEND_REPORTED_USER suspends the reported user; DISMISS_REPORT dismisses the report; ESCALATE moves the report for higher-priority review." }) @ApiBody({ type: UserSafetyAdminActionDto, examples: { markReviewed: { value: { action: 'MARK_REVIEWED', reason: 'REVIEW_COMPLETE', comment: 'Report reviewed and action logged.', notifyReporter: true, notifyReportedUser: false } }, warnReportedUser: { value: { action: 'WARN_REPORTED_USER', reason: 'HARASSMENT_CONFIRMED', comment: 'Reported user warned for harassment.', notifyReporter: true, notifyReportedUser: true } }, suspendReportedUser: { value: { action: 'SUSPEND_REPORTED_USER', reason: 'REPEATED_HARASSMENT', comment: 'Reported user suspended after repeated safety violations.', notifyReporter: true, notifyReportedUser: true } }, dismissReport: { value: { action: 'DISMISS_REPORT', reason: 'INSUFFICIENT_EVIDENCE', comment: 'Report dismissed after review.', notifyReporter: true, notifyReportedUser: false } }, escalate: { value: { action: 'ESCALATE', reason: 'TRUST_AND_SAFETY_REVIEW', comment: 'Escalated for senior trust and safety review.', notifyReporter: false, notifyReportedUser: false } } } }) @ApiResponse({ status: 200, description: 'User safety action completed successfully', schema: { example: { success: true, data: { id: 'report_id', status: 'WARNED', action: 'WARN_REPORTED_USER' }, message: 'User safety action completed successfully.' } } }) action(@CurrentUser() user: AuthUserContext, @Param('id') id: string, @Body() dto: UserSafetyAdminActionDto) { return this.service.action(user, id, dto); } }
