import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { SocialModerationAction, SocialReportReason, SocialReportingEscalationRule } from '@prisma/client';
import { Type } from 'class-transformer';
import { IsBoolean, IsEnum, IsISO8601, IsInt, IsOptional, IsString, Max, Min } from 'class-validator';
export enum SocialRange { LAST_24_HOURS='LAST_24_HOURS', LAST_7_DAYS='LAST_7_DAYS', LAST_30_DAYS='LAST_30_DAYS', CUSTOM='CUSTOM' }
export enum AllSocialReportReason { ALL='ALL', SPAM='SPAM', HARASSMENT='HARASSMENT', HATE_SPEECH='HATE_SPEECH', FALSE_INFORMATION='FALSE_INFORMATION', INAPPROPRIATE='INAPPROPRIATE', OTHER='OTHER' }
export enum AllSocialReportStatus { ALL='ALL', PENDING='PENDING', REVIEWED='REVIEWED', HIDDEN='HIDDEN', REMOVED='REMOVED', WARNED='WARNED', DISMISSED='DISMISSED' }
export enum AllSocialSeverity { ALL='ALL', LOW='LOW', MEDIUM='MEDIUM', HIGH='HIGH', CRITICAL='CRITICAL' }
export enum SocialSortBy { CREATED_AT='createdAt', REPORT_COUNT='reportCount', SEVERITY='severity' }
export enum RuleSortBy { CREATED_AT='createdAt', LAST_MODIFIED_AT='lastModifiedAt', AUTO_FLAG_THRESHOLD='autoFlagThreshold' }
export enum SortOrder { ASC='ASC', DESC='DESC' }
export enum ExportFormat { CSV='CSV', PDF='PDF' }
class PageDto { @ApiPropertyOptional({ example: 1 }) @IsOptional() @Type(() => Number) @IsInt() @Min(1) page?: number; @ApiPropertyOptional({ example: 20 }) @IsOptional() @Type(() => Number) @IsInt() @Min(1) @Max(100) limit?: number; }
export class SocialModerationStatsDto { @ApiPropertyOptional({ enum: SocialRange }) @IsOptional() @IsEnum(SocialRange) range?: SocialRange; @ApiPropertyOptional() @IsOptional() @IsISO8601() fromDate?: string; @ApiPropertyOptional() @IsOptional() @IsISO8601() toDate?: string; }
export class ListSocialReportsDto extends PageDto { @ApiPropertyOptional() @IsOptional() @IsString() search?: string; @ApiPropertyOptional({ enum: AllSocialReportReason }) @IsOptional() @IsEnum(AllSocialReportReason) reportType?: AllSocialReportReason; @ApiPropertyOptional({ enum: AllSocialReportStatus }) @IsOptional() @IsEnum(AllSocialReportStatus) status?: AllSocialReportStatus; @ApiPropertyOptional({ enum: AllSocialSeverity }) @IsOptional() @IsEnum(AllSocialSeverity) severity?: AllSocialSeverity; @ApiPropertyOptional() @IsOptional() @IsISO8601() fromDate?: string; @ApiPropertyOptional() @IsOptional() @IsISO8601() toDate?: string; @ApiPropertyOptional({ enum: SocialSortBy }) @IsOptional() @IsEnum(SocialSortBy) sortBy?: SocialSortBy; @ApiPropertyOptional({ enum: SortOrder }) @IsOptional() @IsEnum(SortOrder) sortOrder?: SortOrder; }
export class ExportSocialReportsDto extends ListSocialReportsDto { @ApiPropertyOptional({ enum: ExportFormat }) @IsOptional() @IsEnum(ExportFormat) format?: ExportFormat; }
export class SocialModerationActionDto { @ApiProperty({ enum: SocialModerationAction }) @IsEnum(SocialModerationAction) action!: SocialModerationAction; @ApiPropertyOptional({ enum: SocialReportReason }) @IsOptional() @IsEnum(SocialReportReason) reason?: SocialReportReason; @ApiPropertyOptional() @IsOptional() @IsString() comment?: string; @ApiPropertyOptional() @IsOptional() @IsBoolean() notifyUser?: boolean; }
export class ListSocialReportingRulesDto extends PageDto { @ApiPropertyOptional() @IsOptional() @IsString() search?: string; @ApiPropertyOptional() @IsOptional() @Type(() => Boolean) @IsBoolean() isActive?: boolean; @ApiPropertyOptional() @IsOptional() @IsString() reportCategory?: string; @ApiPropertyOptional({ enum: RuleSortBy }) @IsOptional() @IsEnum(RuleSortBy) sortBy?: RuleSortBy; @ApiPropertyOptional({ enum: SortOrder }) @IsOptional() @IsEnum(SortOrder) sortOrder?: SortOrder; }
export class CreateSocialReportingRuleDto { @ApiProperty() @IsString() reportCategory!: string; @ApiProperty() @IsString() label!: string; @ApiPropertyOptional() @IsOptional() @IsString() description?: string; @ApiPropertyOptional() @IsOptional() @IsString() iconKey?: string; @ApiProperty() @Type(() => Number) @IsInt() @Min(1) autoFlagThreshold!: number; @ApiProperty({ enum: SocialReportingEscalationRule }) @IsEnum(SocialReportingEscalationRule) escalationRule!: SocialReportingEscalationRule; @ApiPropertyOptional() @IsOptional() @IsBoolean() isActive?: boolean; }
export class UpdateSocialReportingRuleDto { @ApiPropertyOptional() @IsOptional() @IsString() label?: string; @ApiPropertyOptional() @IsOptional() @IsString() description?: string; @ApiPropertyOptional() @IsOptional() @IsString() iconKey?: string; @ApiPropertyOptional() @IsOptional() @Type(() => Number) @IsInt() @Min(1) autoFlagThreshold?: number; @ApiPropertyOptional({ enum: SocialReportingEscalationRule }) @IsOptional() @IsEnum(SocialReportingEscalationRule) escalationRule?: SocialReportingEscalationRule; @ApiPropertyOptional() @IsOptional() @IsBoolean() isActive?: boolean; }
export class UpdateSocialReportingRuleStatusDto { @ApiProperty() @IsBoolean() isActive!: boolean; @ApiPropertyOptional() @IsOptional() @IsString() reason?: string; }
export class ExportSocialRulesDto { @ApiPropertyOptional({ enum: ExportFormat }) @IsOptional() @IsEnum(ExportFormat) format?: ExportFormat; @ApiPropertyOptional() @IsOptional() @Type(() => Boolean) @IsBoolean() isActive?: boolean; }
