import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { MessageModerationFlagType, MessageModerationSeverity, MessageModerationSource, MessageModerationStatus } from '@prisma/client';
import { Type } from 'class-transformer';
import { IsBoolean, IsEnum, IsISO8601, IsInt, IsOptional, IsString, Max, MaxLength, Min } from 'class-validator';
export enum ModerationAll { ALL='ALL' }
export enum ModerationSortBy { FLAGGED_AT='flaggedAt', SEVERITY='severity', LAST_MESSAGE_AT='lastMessageAt' }
export enum SortOrder { ASC='ASC', DESC='DESC' }
export class ListMessageModerationDto { @ApiPropertyOptional() @IsOptional() @Type(()=>Number) @IsInt() @Min(1) page?:number; @ApiPropertyOptional() @IsOptional() @Type(()=>Number) @IsInt() @Min(1) @Max(100) limit?:number; @ApiPropertyOptional() @IsOptional() @IsString() search?:string; @ApiPropertyOptional({enum:{...MessageModerationSource,...ModerationAll}}) @IsOptional() source?: MessageModerationSource|ModerationAll; @ApiPropertyOptional({enum:{...MessageModerationFlagType,...ModerationAll}}) @IsOptional() flagType?:MessageModerationFlagType|ModerationAll; @ApiPropertyOptional({enum:{...MessageModerationStatus,...ModerationAll}}) @IsOptional() status?:MessageModerationStatus|ModerationAll; @ApiPropertyOptional({enum:{...MessageModerationSeverity,...ModerationAll}}) @IsOptional() severity?:MessageModerationSeverity|ModerationAll; @ApiPropertyOptional() @IsOptional() @IsString() assignedToId?:string; @ApiPropertyOptional() @IsOptional() @IsISO8601() fromDate?:string; @ApiPropertyOptional() @IsOptional() @IsISO8601() toDate?:string; @ApiPropertyOptional({enum:ModerationSortBy}) @IsOptional() @IsEnum(ModerationSortBy) sortBy?:ModerationSortBy; @ApiPropertyOptional({enum:SortOrder}) @IsOptional() @IsEnum(SortOrder) sortOrder?:SortOrder; }
export class BlockMessageDto { @ApiProperty() @IsString() reason!:string; @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(1000) internalNote?:string; @ApiPropertyOptional() @IsOptional() @IsBoolean() notifyUser?:boolean; }
export class WarnUserDto { @ApiProperty() @IsString() reason!:string; @ApiProperty() @IsString() @MaxLength(1000) warningMessage!:string; @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(1000) internalNote?:string; @ApiPropertyOptional() @IsOptional() @IsBoolean() notifyUser?:boolean; }
export class SuspendAccountDto { @ApiProperty() @IsString() reason!:string; @ApiPropertyOptional({example:'TEMPORARY'}) @IsOptional() @IsString() duration?:string; @ApiPropertyOptional() @IsOptional() @IsISO8601() suspendUntil?:string; @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(1000) internalNote?:string; @ApiPropertyOptional() @IsOptional() @IsBoolean() notifyUser?:boolean; }
export class DismissFlagDto { @ApiProperty() @IsString() reason!:string; @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(1000) internalNote?:string; }
export class InternalNoteDto { @ApiProperty() @IsString() @MaxLength(1000) note!:string; }
export class ReprocessMessageDto { @ApiPropertyOptional() @IsOptional() @IsString() @MaxLength(500) reason?:string; }
