import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { CustomerEvent, CustomerEventReminderChannel, CustomerEventReminderFrequency, CustomerEventReminderJobStatus, CustomerEventReminderTiming, CustomerEventType, Prisma } from '@prisma/client';
import { AuthUserContext } from '../../common/decorators/current-user.decorator';
import { PrismaService } from '../../database/prisma.service';
import { CalendarEventsDto, CreateCustomerEventDto, EventSortBy, EventTypeFilter, ListCustomerEventsDto, ReminderChannelDto, SortOrder, UpcomingEventsDto, UpdateCustomerEventDto, UpdateReminderSettingsDto } from './dto/customer-events.dto';

type ContactView = { id: string; name: string; relationship: string | null; phone?: string | null; email?: string | null; avatarUrl: string | null };
type EventWithRecipient = CustomerEvent & { recipient?: ContactView | null };

@Injectable()
export class CustomerEventsService {
  constructor(private readonly prisma: PrismaService) {}
  async list(user: AuthUserContext, query: ListCustomerEventsDto) { const page = query.page ?? 1; const limit = query.limit ?? 20; const where = this.where(user.uid, query); const [items, total] = await this.prisma.$transaction([this.prisma.customerEvent.findMany({ where, include: this.include(), orderBy: this.orderBy(query.sortBy, query.sortOrder), skip: (page - 1) * limit, take: limit }), this.prisma.customerEvent.count({ where })]); return { data: items.map((event) => this.toListItem(event)), meta: { page, limit, total, totalPages: Math.ceil(total / limit) }, message: 'Events fetched successfully' }; }
  async calendar(user: AuthUserContext, query: CalendarEventsDto) { const from = new Date(Date.UTC(query.year, query.month - 1, 1)); const to = new Date(Date.UTC(query.year, query.month, 1)); const events = await this.prisma.customerEvent.findMany({ where: { userId: user.uid, deletedAt: null, eventDate: { gte: from, lt: to }, ...this.eventTypeWhere(query.eventType) }, include: this.include(), orderBy: { eventDate: 'asc' } }); const grouped = new Map<string, { date: string; eventCount: number; eventTypes: Set<CustomerEventType> }>(); for (const event of events) { const date = event.eventDate.toISOString().slice(0, 10); const item = grouped.get(date) ?? { date, eventCount: 0, eventTypes: new Set<CustomerEventType>() }; item.eventCount += 1; item.eventTypes.add(event.eventType); grouped.set(date, item); } return { data: { month: query.month, year: query.year, markedDates: [...grouped.values()].map((item) => ({ date: item.date, eventCount: item.eventCount, eventTypes: [...item.eventTypes] })), events: events.map((event) => this.toCalendarItem(event)) }, message: 'Calendar events fetched successfully' }; }
  async upcoming(user: AuthUserContext, query: UpcomingEventsDto) { const limit = query.limit ?? 10; const daysAhead = query.daysAhead ?? 30; const now = new Date(); const until = new Date(now.getTime() + daysAhead * 24 * 60 * 60 * 1000); const events = await this.prisma.customerEvent.findMany({ where: { userId: user.uid, deletedAt: null, isActive: true, eventDate: { gte: now, lte: until }, ...this.eventTypeWhere(query.eventType) }, include: this.include(), orderBy: { eventDate: 'asc' }, take: limit }); return { data: events.map((event) => ({ ...this.toCalendarItem(event), canSendGift: true })), message: 'Upcoming events fetched successfully' }; }
  async create(user: AuthUserContext, dto: CreateCustomerEventDto) { await this.assertRecipientOwned(user.uid, dto.recipientId); this.assertCustomAlert(dto.reminderTiming, dto.customAlertTime); const eventDate = new Date(dto.eventDate); const channels = dto.channels ?? [ReminderChannelDto.PUSH]; const event = await this.prisma.customerEvent.create({ data: { userId: user.uid, recipientId: dto.recipientId, eventType: dto.eventType, title: dto.title.trim(), eventDate, reminderTiming: dto.reminderTiming ?? CustomerEventReminderTiming.ON_THE_DAY, reminderFrequency: dto.reminderFrequency ?? CustomerEventReminderFrequency.ONE_TIME, customAlertTime: dto.customAlertTime, channelsJson: channels, notes: dto.notes?.trim(), isActive: dto.isActive ?? true, nextReminderAt: this.nextReminderAt(eventDate, dto.reminderTiming ?? CustomerEventReminderTiming.ON_THE_DAY, dto.customAlertTime) }, include: this.include() }); return { data: this.toDetail(event), message: 'Event created successfully' }; }
  async details(user: AuthUserContext, id: string) { return { data: this.toDetail(await this.getOwnedEvent(user.uid, id)), message: 'Event fetched successfully' }; }
  async update(user: AuthUserContext, id: string, dto: UpdateCustomerEventDto) { const existing = await this.getOwnedEvent(user.uid, id); await this.assertRecipientOwned(user.uid, dto.recipientId); this.assertCustomAlert(dto.reminderTiming ?? existing.reminderTiming, dto.customAlertTime ?? existing.customAlertTime ?? undefined); const eventDate = dto.eventDate ? new Date(dto.eventDate) : existing.eventDate; const reminderTiming = dto.reminderTiming ?? existing.reminderTiming; const updated = await this.prisma.customerEvent.update({ where: { id: existing.id }, data: { eventType: dto.eventType, title: dto.title?.trim(), recipientId: dto.recipientId, eventDate: dto.eventDate ? eventDate : undefined, reminderTiming: dto.reminderTiming, reminderFrequency: dto.reminderFrequency, customAlertTime: dto.customAlertTime, channelsJson: dto.channels, notes: dto.notes?.trim(), isActive: dto.isActive, nextReminderAt: this.nextReminderAt(eventDate, reminderTiming, dto.customAlertTime ?? existing.customAlertTime ?? undefined) }, include: this.include() }); await this.cancelPendingJobs(existing.id); return { data: this.toDetail(updated), message: 'Event updated successfully' }; }
  async delete(user: AuthUserContext, id: string) { const existing = await this.getOwnedEvent(user.uid, id); await this.prisma.customerEvent.delete({ where: { id: existing.id } }); await this.cancelPendingJobs(existing.id); return { message: 'Event deleted successfully.' }; }
  async reminderSettings(user: AuthUserContext, id: string) { return { data: this.toReminderSettings(await this.getOwnedEvent(user.uid, id)), message: 'Reminder settings fetched successfully' }; }
  async updateReminderSettings(user: AuthUserContext, id: string, dto: UpdateReminderSettingsDto) { const existing = await this.getOwnedEvent(user.uid, id); this.assertCustomAlert(dto.reminderTiming ?? existing.reminderTiming, dto.customAlertTime ?? existing.customAlertTime ?? undefined); this.assertChannelRequirements(existing, dto.channels); const channels = dto.channels ? this.channelsFromSettings(dto.channels) : this.channels(existing.channelsJson); const updated = await this.prisma.customerEvent.update({ where: { id: existing.id }, data: { reminderFrequency: dto.reminderFrequency, reminderTiming: dto.reminderTiming, customAlertTime: dto.customAlertTime, channelsJson: channels, nextReminderAt: this.nextReminderAt(existing.eventDate, dto.reminderTiming ?? existing.reminderTiming, dto.customAlertTime ?? existing.customAlertTime ?? undefined) }, include: this.include() }); await this.cancelPendingJobs(existing.id); return { data: this.toReminderSettings(updated), message: 'Reminder settings updated successfully' }; }
  private where(userId: string, query: ListCustomerEventsDto): Prisma.CustomerEventWhereInput { return { userId, deletedAt: null, recipientId: query.recipientId, eventDate: query.fromDate || query.toDate ? { ...(query.fromDate ? { gte: new Date(query.fromDate) } : {}), ...(query.toDate ? { lte: new Date(query.toDate) } : {}) } : undefined, ...this.eventTypeWhere(query.eventType), ...(query.search ? { OR: [{ title: { contains: query.search, mode: 'insensitive' } }, { notes: { contains: query.search, mode: 'insensitive' } }] } : {}) }; }
  private eventTypeWhere(eventType?: EventTypeFilter): Prisma.CustomerEventWhereInput { return eventType && eventType !== EventTypeFilter.ALL ? { eventType } : {}; }
  private orderBy(sortBy?: EventSortBy, sortOrder?: SortOrder): Prisma.CustomerEventOrderByWithRelationInput { return { [sortBy ?? EventSortBy.EVENT_DATE]: sortOrder === SortOrder.DESC ? 'desc' : 'asc' }; }
  private include() { return { recipient: { select: { id: true, name: true, relationship: true, phone: true, email: true, avatarUrl: true } } } as const; }
  private async getOwnedEvent(userId: string, id: string): Promise<EventWithRecipient> { const event = await this.prisma.customerEvent.findFirst({ where: { id, userId, deletedAt: null }, include: this.include() }); if (!event) throw new NotFoundException('Event not found.'); return event; }
  private async assertRecipientOwned(userId: string, recipientId?: string): Promise<void> { if (!recipientId) return; const contact = await this.prisma.customerContact.findFirst({ where: { id: recipientId, userId, deletedAt: null } }); if (!contact) throw new BadRequestException('Recipient contact not found.'); }
  private assertCustomAlert(timing?: CustomerEventReminderTiming, customAlertTime?: string): void { if (timing === CustomerEventReminderTiming.CUSTOM && !customAlertTime) throw new BadRequestException('customAlertTime is required when reminderTiming is CUSTOM'); }
  private assertChannelRequirements(event: EventWithRecipient, channels?: { push?: boolean; email?: boolean; sms?: boolean }): void { if (!channels) return; if (channels.email && !event.recipient?.email) throw new BadRequestException('Email channel requires recipient email.'); if (channels.sms && !event.recipient?.phone) throw new BadRequestException('SMS channel requires recipient phone.'); }
  private async cancelPendingJobs(eventId: string): Promise<void> { await this.prisma.customerEventReminderJob.updateMany({ where: { eventId, status: CustomerEventReminderJobStatus.PENDING }, data: { status: CustomerEventReminderJobStatus.CANCELLED } }); }
  private nextReminderAt(eventDate: Date, timing: CustomerEventReminderTiming, customAlertTime?: string): Date { const next = new Date(eventDate); if (timing === CustomerEventReminderTiming.ONE_DAY_BEFORE) next.setUTCDate(next.getUTCDate() - 1); if (timing === CustomerEventReminderTiming.THREE_DAYS_BEFORE) next.setUTCDate(next.getUTCDate() - 3); if (timing === CustomerEventReminderTiming.ONE_WEEK_BEFORE) next.setUTCDate(next.getUTCDate() - 7); if (customAlertTime) { const [hour, minute] = customAlertTime.split(':').map(Number); next.setUTCHours(hour, minute, 0, 0); } return next; }
  private daysLeft(date: Date): number { const today = new Date(); const start = Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), today.getUTCDate()); const target = Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()); return Math.ceil((target - start) / (24 * 60 * 60 * 1000)); }
  private channels(value: Prisma.JsonValue): CustomerEventReminderChannel[] { return Array.isArray(value) ? value.filter((item): item is CustomerEventReminderChannel => typeof item === 'string' && ['PUSH', 'EMAIL', 'SMS'].includes(item)) : [CustomerEventReminderChannel.PUSH]; }
  private channelsFromSettings(settings: { push?: boolean; email?: boolean; sms?: boolean }): CustomerEventReminderChannel[] { const channels: CustomerEventReminderChannel[] = []; if (settings.push) channels.push(CustomerEventReminderChannel.PUSH); if (settings.email) channels.push(CustomerEventReminderChannel.EMAIL); if (settings.sms) channels.push(CustomerEventReminderChannel.SMS); return channels.length ? channels : [CustomerEventReminderChannel.PUSH]; }
  private initials(name?: string): string { return (name ?? '').split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]?.toUpperCase() ?? '').join(''); }
  private recipient(contact?: ContactView | null, full = false) { if (!contact) return null; return { id: contact.id, name: contact.name, relationship: contact.relationship, ...(full ? { phone: contact.phone, email: contact.email } : {}), avatarUrl: contact.avatarUrl, initials: this.initials(contact.name) }; }
  private toListItem(event: EventWithRecipient) { return { id: event.id, title: event.title, eventType: event.eventType, eventDate: event.eventDate, daysLeft: this.daysLeft(event.eventDate), recipient: this.recipient(event.recipient), reminderTiming: event.reminderTiming, isActive: event.isActive, createdAt: event.createdAt }; }
  private toCalendarItem(event: EventWithRecipient) { return { id: event.id, title: event.title, eventType: event.eventType, eventDate: event.eventDate, daysLeft: this.daysLeft(event.eventDate), recipient: this.recipient(event.recipient) }; }
  private toDetail(event: EventWithRecipient) { return { ...this.toListItem(event), recipient: this.recipient(event.recipient, true), reminderFrequency: event.reminderFrequency, customAlertTime: event.customAlertTime, channels: this.channels(event.channelsJson), notes: event.notes, updatedAt: event.updatedAt }; }
  private toReminderSettings(event: EventWithRecipient) { const channels = this.channels(event.channelsJson); return { eventId: event.id, reminderFrequency: event.reminderFrequency, reminderTiming: event.reminderTiming, customAlertTime: event.customAlertTime, channels: { push: channels.includes(CustomerEventReminderChannel.PUSH), email: channels.includes(CustomerEventReminderChannel.EMAIL), sms: channels.includes(CustomerEventReminderChannel.SMS) } }; }
}
