import { BadRequestException, Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Prisma, SystemSettings, UploadedFileStatus } from '@prisma/client';
import { AuthUserContext } from '../../../common/decorators/current-user.decorator';
import { AuditLogWriterService } from '../../../common/services/audit-log.service';
import { MailerService } from '../../mailer/mailer.service';
import { ListSystemSettingsAuditLogsDto, SmtpTestDto, UpdateLogoDto, UpdateSystemSettingsDto } from '../dto/system-settings.dto';
import { SystemSettingsRepository } from '../repositories/system-settings.repository';

type SettingsWithUpdater = SystemSettings & { updatedBy?: { id: string; firstName: string; lastName: string } | null };
type PasswordPolicy = { minLength: number; requireUppercase: boolean; requireLowercase: boolean; requireNumber: boolean; requireSymbol: boolean };
@Injectable()
export class SystemSettingsService {
  constructor(private readonly repository: SystemSettingsRepository, private readonly auditLog: AuditLogWriterService, private readonly configService: ConfigService, private readonly mailer: MailerService) {}
  async get() { const settings = await this.getOrCreate(); return { data: this.toView(settings), message: 'System settings fetched successfully.' }; }
  async update(user: AuthUserContext, dto: UpdateSystemSettingsDto, ipAddress?: string, userAgent?: string | string[]) { const current = await this.getOrCreate(); const before = this.toAuditView(current); const updated = await this.repository.updateSettings(current.id, { applicationName: dto.platformInfo.applicationName, supportEmail: dto.platformInfo.supportEmail, platformLogoUrl: dto.platformInfo.platformLogoUrl, sessionTimeoutMinutes: dto.security.sessionTimeoutMinutes, adminMfaRequired: dto.security.adminMfaRequired, passwordPolicyJson: dto.security.passwordPolicy as unknown as Prisma.InputJsonValue, defaultCurrency: dto.payments.defaultCurrency.toUpperCase(), transactionFeePercent: new Prisma.Decimal(dto.payments.transactionFeePercent), pushNotificationsEnabled: dto.notifications.pushNotificationsEnabled, emailNotificationsEnabled: dto.notifications.emailNotificationsEnabled, updatedById: user.uid }); await this.writeAudit(user, current.id, 'SYSTEM_SETTINGS_UPDATED', before, this.toAuditView(updated), ipAddress, userAgent, { sessionTimeoutAffectsFutureSessionsOnly: true, paymentFeeAffectsFutureTransactionsOnly: true }); return { data: this.toView(updated), message: 'System settings updated successfully.' }; }
  async updateLogo(user: AuthUserContext, dto: UpdateLogoDto, ipAddress?: string, userAgent?: string | string[]) { const current = await this.getOrCreate(); if (dto.uploadId) { const upload = await this.repository.findUploadById(dto.uploadId); if (!upload || upload.status !== UploadedFileStatus.COMPLETED) throw new BadRequestException('Completed logo upload not found'); if (upload.fileUrl !== dto.platformLogoUrl) throw new BadRequestException('platformLogoUrl must match the completed upload URL'); } const before = this.toAuditView(current); const updated = await this.repository.updateSettings(current.id, { platformLogoUrl: dto.platformLogoUrl, updatedById: user.uid }); await this.writeAudit(user, current.id, 'SYSTEM_SETTINGS_LOGO_UPDATED', before, this.toAuditView(updated), ipAddress, userAgent, { uploadId: dto.uploadId ?? null, usesStorageUploadReference: Boolean(dto.uploadId) }); return { data: { platformLogoUrl: updated.platformLogoUrl, uploadId: dto.uploadId ?? null }, message: 'System logo updated successfully.' }; }
  async testSmtp(user: AuthUserContext, dto: SmtpTestDto, ipAddress?: string, userAgent?: string | string[]) { await this.mailer.sendProviderMessageEmail(dto.to, 'Gift App SMTP test', 'This is a Gift App admin SMTP configuration test email.'); await this.writeAudit(user, null, 'SYSTEM_SETTINGS_SMTP_TEST_SENT', null, { to: dto.to, smtpConfigured: this.smtpConfigured() }, ipAddress, userAgent); return { data: { sent: true, to: dto.to, smtpConfigured: this.smtpConfigured() }, message: 'SMTP test email sent successfully.' }; }
  async auditLogs(query: ListSystemSettingsAuditLogsDto) { const page = query.page ?? 1; const limit = Math.min(query.limit ?? 20, 100); const where: Prisma.AdminAuditLogWhereInput = { action: { in: ['SYSTEM_SETTINGS_UPDATED', 'SYSTEM_SETTINGS_LOGO_UPDATED', 'SYSTEM_SETTINGS_SMTP_TEST_SENT'] }, createdAt: { gte: query.fromDate ? new Date(query.fromDate) : undefined, lte: query.toDate ? new Date(query.toDate) : undefined } }; const [items, total] = await this.repository.findAuditLogsWithCount({ where, skip: (page - 1) * limit, take: limit }); return { data: items.map((item) => ({ id: item.id, action: item.action, actor: item.actor ? { id: item.actor.id, name: this.name(item.actor) } : null, before: item.beforeJson ?? null, after: item.afterJson ?? null, createdAt: item.createdAt })), meta: { page, limit, total, totalPages: Math.ceil(total / limit) }, message: 'System settings audit logs fetched successfully.' }; }
  private async getOrCreate(): Promise<SettingsWithUpdater> { const existing = await this.repository.findFirstSettings(); if (existing) return existing; return this.repository.createDefaultSettings({ applicationName: this.configService.get<string>('APP_NAME', 'Gift App'), supportEmail: this.configService.get<string>('APP_SUPPORT_EMAIL', 'support@giftapp.com'), platformLogoUrl: this.configService.get<string>('APP_LOGO_URL'), defaultCurrency: this.configService.get<string>('PAYOUT_DEFAULT_CURRENCY', 'USD') }); }
  private toView(settings: SettingsWithUpdater) { return { platformInfo: { applicationName: settings.applicationName, supportEmail: settings.supportEmail, platformLogoUrl: settings.platformLogoUrl }, security: { sessionTimeoutMinutes: settings.sessionTimeoutMinutes, adminMfaRequired: settings.adminMfaRequired, passwordPolicy: this.passwordPolicy(settings.passwordPolicyJson) }, payments: { defaultCurrency: settings.defaultCurrency, transactionFeePercent: this.money(settings.transactionFeePercent) }, notifications: { pushNotificationsEnabled: settings.pushNotificationsEnabled, emailNotificationsEnabled: settings.emailNotificationsEnabled, smtpConfigured: this.smtpConfigured() } }; }
  private toAuditView(settings: SettingsWithUpdater) { return this.toView(settings); }
  private passwordPolicy(value: Prisma.JsonValue): PasswordPolicy { if (!value || typeof value !== 'object' || Array.isArray(value)) return { minLength: 8, requireUppercase: true, requireLowercase: true, requireNumber: true, requireSymbol: true }; const record = value as Record<string, unknown>; return { minLength: Number(record.minLength ?? 8), requireUppercase: Boolean(record.requireUppercase ?? true), requireLowercase: Boolean(record.requireLowercase ?? true), requireNumber: Boolean(record.requireNumber ?? true), requireSymbol: Boolean(record.requireSymbol ?? true) }; }
  private smtpConfigured(): boolean { return ['MAIL_HOST', 'MAIL_USERNAME', 'MAIL_PASSWORD', 'MAIL_FROM_ADDRESS'].every((key) => Boolean(this.configService.get<string>(key))); }
  private async writeAudit(user: AuthUserContext, targetId: string | null, action: string, beforeJson: unknown, afterJson: unknown, ipAddress?: string, userAgent?: string | string[], metadataJson?: unknown) { await this.auditLog.write({ actorId: user.uid, targetId, targetType: 'SYSTEM_SETTINGS', action, module: 'System Settings', beforeJson, afterJson, metadataJson, ipAddress, userAgent: Array.isArray(userAgent) ? userAgent.join(', ') : userAgent }); }
  private money(value: Prisma.Decimal | number): number { return Number(Number(value).toFixed(2)); }
  private name(user: { firstName: string; lastName: string }): string { return `${user.firstName} ${user.lastName}`.trim(); }
}
