import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { IsEnum, IsISO8601, IsNumber, IsOptional, IsString, Min } from 'class-validator';
export enum EarningsSummaryRange { LAST_7_DAYS = 'LAST_7_DAYS', LAST_30_DAYS = 'LAST_30_DAYS', LAST_90_DAYS = 'LAST_90_DAYS', ALL_TIME = 'ALL_TIME', CUSTOM = 'CUSTOM' }
export enum EarningsChartRange { DAILY = 'DAILY', WEEKLY = 'WEEKLY', MONTHLY = 'MONTHLY' }
export enum EarningsLedgerTypeFilter { ALL = 'ALL', ORDER_EARNING = 'ORDER_EARNING', REFUND_DEDUCTION = 'REFUND_DEDUCTION', PENALTY = 'PENALTY', PAYOUT = 'PAYOUT', ADJUSTMENT = 'ADJUSTMENT' }
export enum EarningsLedgerStatusFilter { ALL = 'ALL', PENDING = 'PENDING', AVAILABLE = 'AVAILABLE', PAID = 'PAID', FAILED = 'FAILED' }
export enum PayoutHistoryRange { ALL_TIME = 'ALL_TIME', LAST_30_DAYS = 'LAST_30_DAYS', LAST_90_DAYS = 'LAST_90_DAYS', CUSTOM = 'CUSTOM' }
export enum PayoutStatusFilter { ALL = 'ALL', PENDING = 'PENDING', PROCESSING = 'PROCESSING', COMPLETED = 'COMPLETED', FAILED = 'FAILED', CANCELLED = 'CANCELLED' }
export enum PayoutSortBy { createdAt = 'createdAt', amount = 'amount' }
export enum SortOrder { ASC = 'ASC', DESC = 'DESC' }
export class EarningsSummaryQueryDto { @ApiPropertyOptional({ enum: EarningsSummaryRange }) @IsOptional() @IsEnum(EarningsSummaryRange) range?: EarningsSummaryRange; @ApiPropertyOptional() @IsOptional() @IsISO8601() fromDate?: string; @ApiPropertyOptional() @IsOptional() @IsISO8601() toDate?: string; }
export class EarningsChartQueryDto { @ApiPropertyOptional({ enum: EarningsChartRange }) @IsOptional() @IsEnum(EarningsChartRange) range?: EarningsChartRange; @ApiPropertyOptional() @IsOptional() @IsISO8601() fromDate?: string; @ApiPropertyOptional() @IsOptional() @IsISO8601() toDate?: string; }
export class EarningsLedgerQueryDto extends EarningsSummaryQueryDto { @ApiPropertyOptional({ example: 1 }) @IsOptional() @Type(() => Number) @IsNumber() @Min(1) page?: number; @ApiPropertyOptional({ example: 20 }) @IsOptional() @Type(() => Number) @IsNumber() @Min(1) limit?: number; @ApiPropertyOptional({ enum: EarningsLedgerTypeFilter }) @IsOptional() @IsEnum(EarningsLedgerTypeFilter) type?: EarningsLedgerTypeFilter; @ApiPropertyOptional({ enum: EarningsLedgerStatusFilter }) @IsOptional() @IsEnum(EarningsLedgerStatusFilter) status?: EarningsLedgerStatusFilter; }
export class PayoutHistoryQueryDto { @ApiPropertyOptional({ example: 1 }) @IsOptional() @Type(() => Number) @IsNumber() @Min(1) page?: number; @ApiPropertyOptional({ example: 20 }) @IsOptional() @Type(() => Number) @IsNumber() @Min(1) limit?: number; @ApiPropertyOptional({ enum: PayoutHistoryRange }) @IsOptional() @IsEnum(PayoutHistoryRange) range?: PayoutHistoryRange; @ApiPropertyOptional() @IsOptional() @IsISO8601() fromDate?: string; @ApiPropertyOptional() @IsOptional() @IsISO8601() toDate?: string; @ApiPropertyOptional({ enum: PayoutStatusFilter }) @IsOptional() @IsEnum(PayoutStatusFilter) status?: PayoutStatusFilter; @ApiPropertyOptional({ enum: PayoutSortBy }) @IsOptional() @IsEnum(PayoutSortBy) sortBy?: PayoutSortBy; @ApiPropertyOptional({ enum: SortOrder }) @IsOptional() @IsEnum(SortOrder) sortOrder?: SortOrder; }
export class PayoutPreviewQueryDto { @ApiProperty({ example: 1250 }) @Type(() => Number) @IsNumber() @Min(0.01) amount!: number; @ApiPropertyOptional({ example: 'payout_method_id' }) @IsOptional() @IsString() payoutMethodId?: string; }
export class RequestProviderPayoutDto { @ApiProperty({ example: 1250 }) @Type(() => Number) @IsNumber() @Min(0.01) amount!: number; @ApiProperty({ example: 'payout_method_id' }) @IsString() payoutMethodId!: string; @ApiProperty({ example: 'provider_payout_2026_001' }) @IsString() idempotencyKey!: string; }
export class CancelProviderPayoutDto { @ApiPropertyOptional({ example: 'Requested by provider.' }) @IsOptional() @IsString() reason?: string; }
